### ISSUE TITLE
Should this be folded into ember-study?

### ISSUE THREAD

**Issue by berziiii** [ga-wdi-boston/ember-routing-study#14]
@gaand asks @jrhorn424 please?

**Comment by GA-MEB** [comment]
At the moment, the answer to this question appears to be "no". `ember-study` is a more high-level introduction to concepts of front-end frameworks, such as view state and routing, while `ember-routing-study` is a more detailed treatment of routing. Additionally, their being split allows for the content to be broken out over multiple days.

**Comment by gaand** [comment]
@jrhorn424 Based on your thumbs up above, and my belief that I asked @berziiii to open this,  I"m closing.
